import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Navbar01, Navbar01NavLink } from "@/components/mini/navbar";
import { getSession } from "./actions/session";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const session = await getSession()

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar01
          navigationLinks={defaultNavigationLinks}
          signInHref="/login"
          signInText={!session ? "Masuk" : undefined}
          ctaHref={!session ? "/register" : "/logout"}
          ctaText={!session ? 'Daftar' : 'Keluar'}
        />
        {children}
      </body>
    </html>
  );
}

// Default navigation links
const defaultNavigationLinks: Navbar01NavLink[] = [
  { href: '/', label: 'Home', },
  { href: '/panitia', label: 'Panitia' },
  { href: '/peserta', label: 'Peserta' },
  { href: '/admin', label: 'Admin' },
];